language: android
jdk: oraclejdk7
env:
    matrix:
        - ANDROID_TARGET=android-21 ANDROID_ABI=armeabi-v7a

android:
    components:
        - build-tools-21.1.1
        - android-21
        - extra
        
before_script:
    - chmod +x ./gradlew
    # Create and start emulator
    - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
    - emulator -avd test -no-skin -no-audio -no-window &

install:
    # Check install section: http://docs.travis-ci.com/user/build-configuration/#install
    # If you'd like to skip the install stage entirely, set it to true and nothing will be run.
    - true

script:
    # By default Travis-ci executes './gradlew build connectedCheck' if no 'script:' section found.
    - ./gradlew build


